#!/bin/sh
# ::::::::  :::    ::: ::::::::::: ::::::::   ::::::::  ::: ::::::::            :::::::::   ::::::::  :::::::::  :::       ::: ::::    ::::  :::::::::   ::::::::  
#:+:    :+: :+:    :+:     :+:    :+:    :+: :+:    :+: :+ :+:    :+:           :+:    :+: :+:    :+: :+:    :+: :+:       :+: +:+:+: :+:+:+ :+:    :+: :+:    :+: 
#+:+    +:+ +:+    +:+     +:+    +:+    +:+       +:+     +:+                  +:+    +:+ +:+        +:+    +:+ +:+       +:+ +:+ +:+:+ +:+ +:+    +:+ +:+        
#+#+    +:+ +#++:++#++     +#+    +#+    +:+     +#+       +#++:++#++           +#++:++#+  +#++:++#++ +#++:++#+  +#+  +:+  +#+ +#+  +:+  +#+ +#++:++#:  +#+        
#+#+    +#+ +#+    +#+     +#+    +#+    +#+   +#+                +#+           +#+    +#+        +#+ +#+        +#+ +#+#+ +#+ +#+       +#+ +#+    +#+ +#+        
##+#    #+# #+#    #+#     #+#    #+#    #+#  #+#          #+#    #+#           #+#    #+# #+#    #+# #+#         #+#+# #+#+#  #+#       #+# #+#    #+# #+#    #+# 
# ########  ###    ### ########### ########  ##########     ########            #########   ########  ###          ###   ###   ###       ### ###    ###  ########  
$HOME/.local/bin/locker &
nitrogen --restore &
picom &
sxhkd &
$HOME/.config/polybar/launch.sh &
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config normal_border_color \#990099
bspc config active_border_color \#FFB6C1
bspc config border_width         2
bspc config window_gap           12 

bspc config split_ratio          0.32
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# i guess we don't want this happening? ^

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave desktop='^2' state=fullscreen
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a lxappearence state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Polybar 
bspc rule -a Zathura state=fullscreen
